server {
    listen 80;
    server_name nova.hacheinteractive.com;
    root /var/www/nova.hacheinteractive.com/app/public;
    index index.php;
    add_header X-Robots-Tag "noindex, nofollow" always;
    location / { try_files $uri $uri/ /index.php?$query_string; }
    location ~ \.php$ { include snippets/fastcgi-php.conf; fastcgi_pass unix:/run/php/php8.4-fpm.sock; }
    location ~ /\. { deny all; }
}
